typography_spectrum: 0.5
style: the-composer
content_rating:
  adult: true
color:
  brandColors:
    - '#040001'
    - '#3a2e32'
    - '#e1d3c8'
    - '#b16448'
    - '#b73132'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.36898
analytics:
  google: null
  facebook: null
  twitter: null
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/f9db9d08-a986-4394-b8b3-5ecb154daabf.svg'
name: asdf
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/5fc30053-d635-4134-b7e9-bf32a5549f85.svg'
purposes:
  - awareness
title: WTF
purpose: []
